// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Practise;
using System;
using REST.Models;

namespace Practise.Configurations
{
    public partial class CommentsConfiguration : IEntityTypeConfiguration<comments>
    {
        public void Configure(EntityTypeBuilder<comments> entity)
        {
            entity.HasKey(e => e.id_comment)
                .HasName("PK__comments__7E14AC854C2032DC");

            entity.ToTable("comments");

            entity.Property(e => e.id_comment).HasColumnName("id_comment");

            entity.Property(e => e.comment).HasColumnName("comment");

            entity.Property(e => e.id_user)
                .HasColumnName("id_user");

            entity.Property(e => e.id_video)
                .HasColumnName("id_video");

            entity.Property(e => e.fecha_carga)
                            .HasColumnName("fecha_carga");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<comments> entity);
    }
}
