// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Practise;
using System;
using REST.Models;

namespace Practise.Configurations
{
    public partial class VideosConfiguration : IEntityTypeConfiguration<videos>
    {
        public void Configure(EntityTypeBuilder<videos> entity)
        {
            entity.HasKey(e => e.id_video)
                .HasName("PK__videos__2B9E8C402704684B");

            entity.ToTable("videos");

            entity.Property(e => e.id_video).HasColumnName("id_video");

            entity.Property(e => e.paths).HasColumnName("paths");

            entity.Property(e => e.title)
                .HasColumnName("title");

            entity.Property(e => e.description)
                .HasColumnName("description");

            entity.Property(e => e.id_user)
                .HasColumnName("id_user");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<videos> entity);
    }
}
